# Generated by Django 5.2.7 on 2025-10-04 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unver', '0002_remove_users_date_joined_remove_users_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unver.roles'),
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
