# Generated by Django 5.2.7 on 2025-10-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unver', '0002_role_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
