# Generated by Django 5.2.7 on 2025-10-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unver', '0003_remove_user_role_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
