# Generated by Django 5.2.7 on 2025-10-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unver', '0004_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
